### ISSUE TITLE
Extract complex VectorData to its own type: TimeSeriesRef

### ISSUE THREAD

**Issue by rly** [oruebel/ndx-icephys-meta#60]
The `IntracellularStimuliTable` and `IntracellularResponsesTable` types both have a dataset:
```yaml
- name: stimulus
  neurodata_type_inc: VectorData
  dtype:
  - name: idx_start
    dtype: int32
    doc: Start index into the TimeSeries 'data' and 'timestamp' datasets of the
      referenced TimeSeries. The first dimension of those arrays is always time.
  - name: count
    dtype: int32
    doc: Number of data samples available in this time series, during this epoch
  - name: timeseries
    dtype:
      target_type: TimeSeries
      reftype: object
    doc: The TimeSeries that this index applies to
  doc: Column storing the reference to the recorded stimulus for the recording
    (rows)
```

Aside from the name and docstring, this is the same as the definition for the `'timeseries'` column of the `TimeIntervals` table. Since this exact structure would now be used three times in the schema, I think this should be its own type named something like `TimeSeriesRef` or `TimeSeriesColumn` and included in the table, e.g.:
```yaml
- name: stimulus
  neurodata_type_inc: TimeSeriesRef
  doc: Column storing the reference to the recorded stimulus for the recording
    (rows)
```
